### ISSUE TITLE
Support for prelease versions like 1.0.0-beta.1

### ISSUE THREAD

**Issue by mmun** [lytics/ember-cli-release#20]
See https://github.com/npm/node-semver#prerelease-identifiers

**Comment by slindberg** [comment]
I'd like to support this for sure. A good use case is:

`0.1.0` → `1.0.0-beta.0` → `1.0.0-beta.1` → `1.0.0`

The question is what series of `ember release` commands results in these versions?

One possibility:

```sh
# New version, v0.1.0
$ ember release

# Adds 'beta' suffix starting at 0, assumes major version update, v1.0.0-beta.0
$ ember release --pre beta

# Increments pre-release version,  v1.0.0-beta.1
$ ember release

# Removes prerelease suffix, v1.0.0
$ ember release --major
```

Questions:

- Should adding the `--pre` flag imply `--major`?
- What happens when its used with a version over 1.0.0? Is the transition to 1.0.0 the only use case for prerelease versions (e.g. 2.0.0-beta.0)?
- Should `--pre` be required to increment the prerelease?
- What happens when `--minor` is used when version is a prerelease?
- How should changing the suffix be handled (e.g. 1.0.0-beta.5 → 1.0.0-rc.0)?
- Should prerelease increments start at `0` as the spec implies, or `1` as Ember has done in the past?

**Comment by mmun** [comment]
It seems best to stick to the behavior of `semver.inc` to minimize the documentation you need to maintain. With `semver` there is `premajor`, `preminor` and `prepatch` (here's some [tests](https://github.com/npm/node-semver/blob/63c48296ca5da3ba6a88c743bb8c92effc789811/test/index.js#L353-L358)).

I'm not too sure about supporting Ember's numbering. You could allow chaining multiple increment commands, e.g. `ember release --preminor beta --pre beta`. Kind of a mouthful but I wouldn't want to encourage doing it anyways :P

**Comment by mmun** [comment]
A dubious behaviour of `semver` is that using --pre when you're not already in a prerelease version will do a `--prepatch`. See [test](https://github.com/npm/node-semver/blob/63c48296ca5da3ba6a88c743bb8c92effc789811/test/index.js#L336). Arguably that should throw instead.

**Comment by slindberg** [comment]
Hm, this is much stickier than I originally was thinking. I agree that `ember release` should be stricter than semver for happy paths.

I'm going to be AFK for the next couple weeks, so this will unfortunately have to wait a while. If you want to open a PR, I'll see if I can find some time to review next week. Thanks for the input :beers:

**Comment by mmun** [comment]
@slindberg Oh yeah no sweat. I was just starting the conversation :)

**Comment by cibernox** [comment]
I found myself needing this today. Has any work begun on this?

**Comment by mmun** [comment]
It could be a relatively simple PR if we just add command line arguments that map directly to the semver commands.

```
--premajor [name]
--preminor [name]
--prepatch [name]
--prerelease [name]
```

An expected sequence starting at `1.2.3`

```
> ember release --premajor alpha
2.0.0-alpha.0
> ember release --prerelease
2.0.0-alpha.1
> ember release --prerelease beta
2.0.0-beta.0
> ember release --prerelease
2.0.0-beta.1
> ember release --major
2.0.0
```

**Comment by slindberg** [comment]
@cibernox I don't have the bandwidth to work on this, so PRs are definitely welcome.

I like @mmun's KISS suggestion, except that I'd like to keep it so that `ember release` always increments in the least-impactful way by default. For example this is what would happen with the implicit `--patch` argument:

```sh
> ember release --premajor alpha
2.0.0-alpha.0
> ember release
2.0.0
```

Incrementing the version to `2.0.0-alpha.1`, instead of `2.0.0` would be less dangerous for the user.
